version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./certs/dummy.crt:/etc/nginx/dummy.crt
      - ./certs/dummy.key:/etc/nginx/dummy.key
      - ./certs/ca.crt:/etc/nginx/ca.crt
  keycloak:
    container_name: keycloak
    image: keycloak/keycloak:latest
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
      - KC_HTTP_RELATIVE_PATH=/auth
      - KC_HTTP_ENABLED=true
      - KC_HTTPS_CERTIFICATE_FILE=/etc/x509/https/dummy.crt
      - KC_HTTPS_CERTIFICATE_KEY_FILE=/etc/x509/https/dummy.key
    expose:
      - "8443"
    volumes:
      - ./certs:/etc/x509/https  
    command:
      - start-dev 
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data               
volumes:
  keycloak-volume:
    driver: local

networks:
  default:
    name: keycloak-network